"""Initial migration

Revision ID: 902d5f2a2642
Revises: 
Create Date: 2026-07-29 10:43:52.051711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902d5f2a2642'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'icon')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
