"""Add UserMemory and AIRequestLog

Revision ID: 9b7b6d891400
Revises: 902d5f2a2642
Create Date: 2026-08-04 12:19:56.628850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7b6d891400'
down_revision: Union[str, Sequence[str], None] = '902d5f2a2642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=2000), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_request_log_id'), 'ai_request_log', ['id'], unique=False)
    op.create_index(op.f('ix_ai_request_log_user_id'), 'ai_request_log', ['user_id'], unique=False)
    op.create_table('user_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_key', sa.String(length=255), nullable=False),
    sa.Column('memory_value', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memory_category'), 'user_memory', ['category'], unique=False)
    op.create_index(op.f('ix_user_memory_id'), 'user_memory', ['id'], unique=False)
    op.create_index(op.f('ix_user_memory_memory_key'), 'user_memory', ['memory_key'], unique=False)
    op.create_index(op.f('ix_user_memory_user_id'), 'user_memory', ['user_id'], unique=False)
    op.drop_column('notifications', 'category')
    op.drop_column('notifications', 'action_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('action_link', sa.VARCHAR(), nullable=True))
    op.add_column('notifications', sa.Column('category', sa.VARCHAR(), server_default=sa.text("'general'"), nullable=True))
    op.drop_index(op.f('ix_user_memory_user_id'), table_name='user_memory')
    op.drop_index(op.f('ix_user_memory_memory_key'), table_name='user_memory')
    op.drop_index(op.f('ix_user_memory_id'), table_name='user_memory')
    op.drop_index(op.f('ix_user_memory_category'), table_name='user_memory')
    op.drop_table('user_memory')
    op.drop_index(op.f('ix_ai_request_log_user_id'), table_name='ai_request_log')
    op.drop_index(op.f('ix_ai_request_log_id'), table_name='ai_request_log')
    op.drop_table('ai_request_log')
    # ### end Alembic commands ###
